after/autolist/config/routes.rb
Autolist::Application.routes.draw do

  root 'projects#index'

  resources :projects do
    get :autocomplete_user_name, :on => :collection
  end

  post 'projects/:id/add_collaborator' => 'projects#add_collaborator', :as => 'add_collaborator'

  get 'users/index' => 'users#index', :as => 'users'

end

after/autolist/app/models/collaborating.rb
class Collaborating < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

after/autolist/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :collaboratings, :dependent => :destroy
  has_many :collaborators, :through => :collaboratings, :source => :user
end

after/autolist/app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaboratings, :dependent => :destroy
  has_many :collaborated_projects, :through => :collaboratings, :source => :project
end

after/autolist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

after/autolist/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, :only => [:show, :add_collaborator, :destroy]
  autocomplete :user, :name

  def index
    @projects = Project.all
  end

  def show
    @collaborators = @project.collaborators
  end

  def add_collaborator
    @collaborator = User.find_by_name(params[:collab])
    if @collaborator.blank?
      redirect_to @project, :notice => "User does not exist!"
    elsif @project.collaborators.include?(@collaborator)
      redirect_to @project, :notice => "User is already a collaborator!"
    else
      @project.collaborators << @collaborator
      redirect_to @project
    end
  end

  def destroy
    @collaborator = User.find_by_name(params[:collab])
    @project.collaborators.delete(@collaborator)
    redirect_to @project, :notice => "User was deleted successfully!"
  end

  private
  def find_project
    @project = Project.find_by_id(params[:id])
  end
end

after/autolist/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

after/autolist/app/helpers/application_helper.rb
module ApplicationHelper
end

after/autolist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autolist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

after/autolist/app/views/projects/index.html.erb
<div class="container">
  <div class="nav">
    <span>Listing Projects</span>
    <%= link_to "Users", users_path %>
  </div>
  <ul class="wrapper">
    <% @projects.each do |project| %>
    <li>
      <% if project.name == "haoqicat" %>
        <%= image_tag "haoqicat.png" %>
      <% else %>
        <%= image_tag "happycasts.png" %>
      <% end %>
      <%= project.name %>
      <%= link_to 'Add collaborators', project, :class => "btn btn-success right" %>
    </li>
    <% end %>
  </ul>
</div>

after/autolist/app/views/projects/show.html.erb
<div class="container">
  <div class="nav">
    <span>Collaborators</span>
    <%= link_to 'Home', root_path %>
  </div>
  <ul class="collabs wrapper">
    <% if @collaborators.present? %>
      <% @collaborators.each do |user| %>
        <li class="uid-<%= user.id %>">
          <span><%= user.name %></span>
          <%= link_to 'Delete', project_path(:collab => user.name), :method => :delete,
            :class => "btn btn-danger right" %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <%= form_tag add_collaborator_path, :method => :post do %>
    <%= autocomplete_field_tag :collab, '', autocomplete_user_name_projects_path, :size => 25 %>
    <%= button_tag 'Add collaborator', :disabled => true, :class => 'btn btn-success btn-collab' %>
  <% end %>

  <div class="collab-error">
    <%= flash[:notice] %>
  </div>
</div>
<script>
  $('#collab').bind('input', function() {
    $('.btn-collab').attr("disabled", true);
  });
  $('#collab').bind('railsAutocomplete.select', function(){
    $('.btn-collab').attr("disabled", false);
  });
</script>

after/autolist/app/views/users/index.html.erb
<div class="container">
  <div class="nav">
    <span>Listing Users</span>
    <%= link_to "Home", root_path %>
  </div>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= user.name %>
      </li>
    <% end %>
  </ul>
</div>